name: Manual Release Build and Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: npm

      - name: Read version from package.json
        id: read_version
        run: |
          echo "Reading version from package.json..."
          version=$(jq -r '.version' package.json)
          echo "Version: $version"
          echo "::set-output name=VERSION::$version"

      - name: Build Docker Image
        run: docker build --no-cache -t znsio/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }} .

      - name: Push Docker Image
        run: docker push znsio/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }}

      - name: Tag as latest
        run: docker tag znsio/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }} znsio/specmatic-insights-github-build-reporter:latest && docker push znsio/specmatic-insights-github-build-reporter:latest
