name: Manual Release Build and Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Docker Login
        run: echo ${{ secrets.SPECMATIC_DOCKER_HUB_TOKEN }} | docker login -u ${{ vars.SPECMATIC_DOCKER_HUB_USERNAME }} --password-stdin

      - name: Read version from package.json
        id: read_version
        run: |
          echo "Reading version from package.json..."
          version=$(jq -r '.version' package.json)
          echo "VERSION: $version"
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: docker build --no-cache -t specmatic/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }} .

      - name: Push Docker Image
        run: docker push specmatic/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }}

      - name: Tag as latest
        run: docker tag specmatic/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }} specmatic/specmatic-insights-github-build-reporter:latest && docker push specmatic/specmatic-insights-github-build-reporter:latest
